# Generated by Django 4.2.3 on 2023-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=10)),
                ('materials_provided', models.CharField(blank=True, choices=[('Debit card', 'Debit card'), ('Credit card', 'Credit card'), ('Cheque book', 'Cheque book')], max_length=100, null=True)),
            ],
        ),
    ]
