# Generated by Django 4.2.3 on 2023-08-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.subdistrict'),
        ),
    ]
