# Generated by Django 4.2.3 on 2023-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_user_username_alter_user_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Savings', 'Savings'), ('Current', 'Current')], max_length=10),
        ),
    ]
