# Generated by Django 4.2.3 on 2023-08-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_remove_user_username_alter_user_account_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
